
/* Code to register embedded modules for meta path based loading if any. */

#include <Python.h>

/* Use a hex version of our own to compare for versions. We do not care about pre-releases */
#if PY_MICRO_VERSION < 16
#define PYTHON_VERSION (PY_MAJOR_VERSION * 256 + PY_MINOR_VERSION * 16 + PY_MICRO_VERSION)
#else
#define PYTHON_VERSION (PY_MAJOR_VERSION * 256 + PY_MINOR_VERSION * 16 + 15)
#endif

#include "nuitka/constants_blob.h"

#include "nuitka/unfreezing.h"

/* Type bool */
#ifndef __cplusplus
#include "stdbool.h"
#endif

#if 394 > 0
static unsigned char *bytecode_data[394];
#else
static unsigned char **bytecode_data = NULL;
#endif

/* Table for lookup to find compiled or bytecode modules included in this
 * binary or module, or put along this binary as extension modules. We do
 * our own loading for each of these.
 */
extern PyObject *modulecode_PyQt5(PyObject *, struct Nuitka_MetaPathBasedLoaderEntry const *);
extern PyObject *modulecode_PyQt5$QtCore$$45$postLoad(PyObject *, struct Nuitka_MetaPathBasedLoaderEntry const *);
extern PyObject *modulecode___main__(PyObject *, struct Nuitka_MetaPathBasedLoaderEntry const *);

static struct Nuitka_MetaPathBasedLoaderEntry meta_path_loader_entries[] = {
    {"PyQt5", modulecode_PyQt5, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"PyQt5.QtCore", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"PyQt5.QtCore-postLoad", modulecode_PyQt5$QtCore$$45$postLoad, 0, 0, NUITKA_TRANSLATED_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"PyQt5.QtGui", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"PyQt5.QtWidgets", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"PyQt5.sip", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"__main__", modulecode___main__, 0, 0, NUITKA_TRANSLATED_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_asyncio", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_bisect", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_blake2", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_bz2", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_codecs_cn", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_codecs_hk", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_codecs_iso2022", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_codecs_jp", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_codecs_kr", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_codecs_tw", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_contextvars", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_crypt", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_csv", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_ctypes", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_datetime", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_decimal", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_elementtree", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_hashlib", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_heapq", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_json", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_lzma", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_multibytecodec", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_opcode", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_pickle", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_posixsubprocess", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_queue", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_random", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_scproxy", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_sha512", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_socket", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_ssl", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_statistics", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_struct", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_uuid", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_zoneinfo", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"array", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"audioop", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"binascii", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email", NULL, 0, 1694, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email._encoded_words", NULL, 1, 5709, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email._header_value_parser", NULL, 2, 79810, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email._parseaddr", NULL, 3, 12398, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email._policybase", NULL, 4, 14835, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.base64mime", NULL, 5, 3266, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.charset", NULL, 6, 11480, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.contentmanager", NULL, 7, 7392, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.encoders", NULL, 8, 1649, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.errors", NULL, 9, 5938, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.feedparser", NULL, 10, 10636, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.generator", NULL, 11, 12612, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.header", NULL, 12, 16459, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.headerregistry", NULL, 13, 21993, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.iterators", NULL, 14, 1958, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.message", NULL, 15, 37859, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.parser", NULL, 16, 5773, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.policy", NULL, 17, 9666, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.quoprimime", NULL, 18, 7701, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"email.utils", NULL, 19, 9467, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"fcntl", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"grp", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"http", NULL, 20, 6440, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"http.client", NULL, 21, 34918, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"math", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ntpath", NULL, 22, 14569, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pyexpat", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"select", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"termios", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"unicodedata", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"zlib", NULL, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_EXTENSION_MODULE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"__future__", NULL, 23, 4089, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_aix_support", NULL, 24, 3009, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_bootlocale", NULL, 25, 1190, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_bootsubprocess", NULL, 26, 2208, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_collections_abc", NULL, 27, 31669, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_compat_pickle", NULL, 28, 5451, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_compression", NULL, 29, 4161, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_markupbase", NULL, 30, 7734, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_osx_support", NULL, 31, 11546, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_py_abc", NULL, 32, 4619, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_pyio", NULL, 33, 74446, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_sitebuiltins", NULL, 34, 3464, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_strptime", NULL, 35, 15978, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_sysconfigdata__darwin_darwin", NULL, 36, 21082, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_threading_local", NULL, 37, 6469, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"_weakrefset", NULL, 38, 7636, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"abc", NULL, 39, 5738, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"aifc", NULL, 40, 25229, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ast", NULL, 41, 52269, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asynchat", NULL, 42, 6785, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio", NULL, 43, 735, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.base_events", NULL, 44, 51987, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.base_futures", NULL, 45, 1873, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.base_subprocess", NULL, 46, 9375, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.base_tasks", NULL, 47, 1909, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.constants", NULL, 48, 546, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.coroutines", NULL, 49, 6602, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.events", NULL, 50, 28066, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.exceptions", NULL, 51, 2518, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.format_helpers", NULL, 52, 2289, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.futures", NULL, 53, 11794, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.locks", NULL, 54, 14394, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.log", NULL, 55, 191, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.proactor_events", NULL, 56, 24314, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.protocols", NULL, 57, 8579, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.queues", NULL, 58, 8481, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.runners", NULL, 59, 2171, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.selector_events", NULL, 60, 29796, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.sslproto", NULL, 61, 21521, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.staggered", NULL, 62, 4125, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.streams", NULL, 63, 20551, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.subprocess", NULL, 64, 7299, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.tasks", NULL, 65, 24138, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.threads", NULL, 66, 943, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.transports", NULL, 67, 12211, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.trsock", NULL, 68, 8534, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncio.unix_events", NULL, 69, 42020, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"asyncore", NULL, 70, 15999, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"base64", NULL, 71, 16418, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"binhex", NULL, 72, 12928, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"bisect", NULL, 73, 2313, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"bz2", NULL, 74, 11508, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"calendar", NULL, 75, 26994, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"cgi", NULL, 76, 26445, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"cgitb", NULL, 77, 10149, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"chunk", NULL, 78, 4804, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"cmd", NULL, 79, 12639, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"code", NULL, 80, 9879, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"codecs", NULL, 81, 33851, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"codeop", NULL, 82, 6421, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"collections", NULL, 83, 48055, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"collections.abc", NULL, 84, 31668, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"colorsys", NULL, 85, 3223, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"concurrent", NULL, 86, 88, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"concurrent.futures", NULL, 87, 1064, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"concurrent.futures._base", NULL, 88, 22287, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"concurrent.futures.process", NULL, 89, 20705, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"concurrent.futures.thread", NULL, 90, 5725, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"configparser", NULL, 91, 45832, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"contextlib", NULL, 92, 19451, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"contextvars", NULL, 93, 208, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"copy", NULL, 94, 6937, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"copyreg", NULL, 95, 4393, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"crypt", NULL, 96, 3476, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"csv", NULL, 97, 11812, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ctypes", NULL, 98, 16388, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ctypes._aix", NULL, 99, 9799, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ctypes._endian", NULL, 100, 1894, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ctypes.macholib", NULL, 101, 255, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ctypes.macholib.dyld", NULL, 102, 4621, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ctypes.macholib.dylib", NULL, 103, 1865, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ctypes.macholib.framework", NULL, 104, 2145, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ctypes.util", NULL, 105, 8226, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"dataclasses", NULL, 106, 23148, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"datetime", NULL, 107, 58060, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"decimal", NULL, 108, 160573, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"difflib", NULL, 109, 59584, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"dis", NULL, 110, 15783, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings", NULL, 111, 3851, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.aliases", NULL, 112, 6293, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.ascii", NULL, 113, 1846, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.base64_codec", NULL, 114, 2333, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.big5", NULL, 115, 1374, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.big5hkscs", NULL, 116, 1384, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.bz2_codec", NULL, 117, 3222, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.charmap", NULL, 118, 2856, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp037", NULL, 119, 2387, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1006", NULL, 120, 2463, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1026", NULL, 121, 2391, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1125", NULL, 122, 8094, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1140", NULL, 123, 2377, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1250", NULL, 124, 2414, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1251", NULL, 125, 2411, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1252", NULL, 126, 2414, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1253", NULL, 127, 2427, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1254", NULL, 128, 2416, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1255", NULL, 129, 2435, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1256", NULL, 130, 2413, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1257", NULL, 131, 2421, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp1258", NULL, 132, 2419, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp273", NULL, 133, 2373, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp424", NULL, 134, 2417, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp437", NULL, 135, 7811, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp500", NULL, 136, 2387, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp720", NULL, 137, 2484, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp737", NULL, 138, 8133, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp775", NULL, 139, 7841, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp850", NULL, 140, 7472, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp852", NULL, 141, 7849, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp855", NULL, 142, 8102, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp856", NULL, 143, 2449, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp857", NULL, 144, 7452, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp858", NULL, 145, 7442, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp860", NULL, 146, 7790, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp861", NULL, 147, 7805, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp862", NULL, 148, 7994, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp863", NULL, 149, 7805, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp864", NULL, 150, 7949, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp865", NULL, 151, 7805, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp866", NULL, 152, 8138, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp869", NULL, 153, 7829, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp874", NULL, 154, 2515, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp875", NULL, 155, 2384, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp932", NULL, 156, 1376, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp949", NULL, 157, 1376, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.cp950", NULL, 158, 1376, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.euc_jis_2004", NULL, 159, 1390, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.euc_jisx0213", NULL, 160, 1390, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.euc_jp", NULL, 161, 1378, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.euc_kr", NULL, 162, 1378, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.gb18030", NULL, 163, 1380, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.gb2312", NULL, 164, 1378, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.gbk", NULL, 165, 1372, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.hex_codec", NULL, 166, 2320, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.hp_roman8", NULL, 167, 2588, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.hz", NULL, 168, 1370, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.idna", NULL, 169, 5562, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso2022_jp", NULL, 170, 1391, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso2022_jp_1", NULL, 171, 1395, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso2022_jp_2", NULL, 172, 1395, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso2022_jp_2004", NULL, 173, 1401, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso2022_jp_3", NULL, 174, 1395, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso2022_jp_ext", NULL, 175, 1399, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso2022_kr", NULL, 176, 1391, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_1", NULL, 177, 2386, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_10", NULL, 178, 2391, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_11", NULL, 179, 2485, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_13", NULL, 180, 2394, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_14", NULL, 181, 2412, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_15", NULL, 182, 2391, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_16", NULL, 183, 2393, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_2", NULL, 184, 2386, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_3", NULL, 185, 2393, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_4", NULL, 186, 2386, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_5", NULL, 187, 2387, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_6", NULL, 188, 2431, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_7", NULL, 189, 2394, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_8", NULL, 190, 2425, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.iso8859_9", NULL, 191, 2386, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.johab", NULL, 192, 1376, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.koi8_r", NULL, 193, 2438, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.koi8_t", NULL, 194, 2349, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.koi8_u", NULL, 195, 2424, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.kz1048", NULL, 196, 2401, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.latin_1", NULL, 197, 1858, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_arabic", NULL, 198, 7705, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_croatian", NULL, 199, 2433, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_cyrillic", NULL, 200, 2423, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_farsi", NULL, 201, 2367, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_greek", NULL, 202, 2407, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_iceland", NULL, 203, 2426, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_latin2", NULL, 204, 2567, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_roman", NULL, 205, 2424, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_romanian", NULL, 206, 2434, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.mac_turkish", NULL, 207, 2427, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.palmos", NULL, 208, 2414, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.ptcp154", NULL, 209, 2508, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.punycode", NULL, 210, 6272, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.quopri_codec", NULL, 211, 2359, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.raw_unicode_escape", NULL, 212, 1727, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.rot_13", NULL, 213, 2966, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.shift_jis", NULL, 214, 1384, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.shift_jis_2004", NULL, 215, 1394, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.shift_jisx0213", NULL, 216, 1394, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.tis_620", NULL, 217, 2476, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.undefined", NULL, 218, 2060, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.unicode_escape", NULL, 219, 1707, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_16", NULL, 220, 4835, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_16_be", NULL, 221, 1615, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_16_le", NULL, 222, 1615, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_32", NULL, 223, 4728, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_32_be", NULL, 224, 1508, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_32_le", NULL, 225, 1508, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_7", NULL, 226, 1536, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_8", NULL, 227, 1595, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.utf_8_sig", NULL, 228, 4507, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.uu_codec", NULL, 229, 3195, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"encodings.zlib_codec", NULL, 230, 3043, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"enum", NULL, 231, 25983, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"filecmp", NULL, 232, 8460, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"fileinput", NULL, 233, 13753, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"fnmatch", NULL, 234, 3905, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"formatter", NULL, 235, 17502, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"fractions", NULL, 236, 18012, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ftplib", NULL, 237, 28657, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"functools", NULL, 238, 28145, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"genericpath", NULL, 239, 3987, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"getopt", NULL, 240, 6223, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"getpass", NULL, 241, 4163, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"gettext", NULL, 242, 18036, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"glob", NULL, 243, 4507, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"graphlib", NULL, 244, 7531, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"gzip", NULL, 245, 18457, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"hashlib", NULL, 246, 6654, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"heapq", NULL, 247, 14003, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"hmac", NULL, 248, 6763, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"html", NULL, 249, 3079, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"html.entities", NULL, 250, 50484, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"html.parser", NULL, 251, 10818, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"imaplib", NULL, 252, 42375, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"imghdr", NULL, 253, 4103, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"imp", NULL, 254, 9814, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib", NULL, 255, 3787, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib._bootstrap", NULL, 256, 28931, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib._bootstrap_external", NULL, 257, 45133, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib._common", NULL, 258, 1662, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib.abc", NULL, 259, 16780, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib.machinery", NULL, 260, 927, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib.metadata", NULL, 261, 21584, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib.resources", NULL, 262, 6354, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"importlib.util", NULL, 263, 9285, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"inspect", NULL, 264, 81354, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"io", NULL, 265, 3371, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ipaddress", NULL, 266, 62456, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"json", NULL, 267, 12247, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"json.decoder", NULL, 268, 9771, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"json.encoder", NULL, 269, 11094, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"json.scanner", NULL, 270, 1916, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"json.tool", NULL, 271, 2690, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"keyword", NULL, 272, 879, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"linecache", NULL, 273, 3990, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"locale", NULL, 274, 34659, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"logging", NULL, 275, 66282, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"logging.config", NULL, 276, 23220, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"logging.handlers", NULL, 277, 43834, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"lzma", NULL, 278, 12057, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"mailbox", NULL, 279, 60563, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"mailcap", NULL, 280, 6472, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"mimetypes", NULL, 281, 16006, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"modulefinder", NULL, 282, 16091, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"netrc", NULL, 283, 3746, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"nturl2path", NULL, 284, 1709, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"numbers", NULL, 285, 12282, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"opcode", NULL, 286, 5186, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"operator", NULL, 287, 13711, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"os", NULL, 288, 31609, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pathlib", NULL, 289, 44632, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pickle", NULL, 290, 47062, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pickletools", NULL, 291, 67070, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pipes", NULL, 292, 7758, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pkgutil", NULL, 293, 18529, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"platform", NULL, 294, 26366, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"poplib", NULL, 295, 13620, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"posixpath", NULL, 296, 10292, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pprint", NULL, 297, 16793, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pstats", NULL, 298, 23715, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pty", NULL, 299, 3919, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"pyclbr", NULL, 300, 10412, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"queue", NULL, 301, 10826, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"quopri", NULL, 302, 5710, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"random", NULL, 303, 22006, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"re", NULL, 304, 14325, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"reprlib", NULL, 305, 5270, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"rlcompleter", NULL, 306, 5712, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"sched", NULL, 307, 6596, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"secrets", NULL, 308, 2143, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"selectors", NULL, 309, 17208, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"shelve", NULL, 310, 9507, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"shlex", NULL, 311, 7697, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"shutil", NULL, 312, 37803, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"signal", NULL, 313, 2786, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"smtpd", NULL, 314, 26487, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"sndhdr", NULL, 315, 6956, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"socket", NULL, 316, 29051, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"socketserver", NULL, 317, 25478, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"sre_compile", NULL, 318, 15016, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"sre_constants", NULL, 319, 6280, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"sre_parse", NULL, 320, 21566, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"ssl", NULL, 321, 44555, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"stat", NULL, 322, 4335, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"statistics", NULL, 323, 31942, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"string", NULL, 324, 7128, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"stringprep", NULL, 325, 9949, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"struct", NULL, 326, 269, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"subprocess", NULL, 327, 44109, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"symbol", NULL, 328, 2542, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"symtable", NULL, 329, 11129, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"sysconfig", NULL, 330, 16030, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"tarfile", NULL, 331, 63037, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"tempfile", NULL, 332, 23329, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"textwrap", NULL, 333, 13484, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"threading", NULL, 334, 42048, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"timeit", NULL, 335, 11719, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"token", NULL, 336, 2459, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"tokenize", NULL, 337, 17100, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"trace", NULL, 338, 19702, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"traceback", NULL, 339, 20166, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"tracemalloc", NULL, 340, 17898, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"tty", NULL, 341, 1041, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"types", NULL, 342, 9184, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"typing", NULL, 343, 71301, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"urllib", NULL, 344, 84, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"urllib.error", NULL, 345, 2789, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"urllib.parse", NULL, 346, 34848, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"urllib.request", NULL, 347, 72209, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"urllib.response", NULL, 348, 3419, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"urllib.robotparser", NULL, 349, 7290, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"uu", NULL, 350, 3629, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"uuid", NULL, 351, 22473, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"warnings", NULL, 352, 13568, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"wave", NULL, 353, 17836, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"weakref", NULL, 354, 20121, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"webbrowser", NULL, 355, 17097, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"wsgiref", NULL, 356, 680, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"wsgiref.handlers", NULL, 357, 16339, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"wsgiref.headers", NULL, 358, 7697, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"wsgiref.simple_server", NULL, 359, 5264, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"wsgiref.util", NULL, 360, 5358, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"wsgiref.validate", NULL, 361, 14720, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xdrlib", NULL, 362, 8206, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml", NULL, 363, 646, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.dom", NULL, 364, 5492, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.dom.NodeFilter", NULL, 365, 932, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.dom.domreg", NULL, 366, 2813, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.dom.expatbuilder", NULL, 367, 27273, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.dom.minicompat", NULL, 368, 2704, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.dom.minidom", NULL, 369, 56274, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.dom.pulldom", NULL, 370, 10654, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.dom.xmlbuilder", NULL, 371, 12440, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.etree", NULL, 372, 87, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.etree.ElementInclude", NULL, 373, 2397, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.etree.ElementPath", NULL, 374, 8377, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.etree.ElementTree", NULL, 375, 56203, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.etree.cElementTree", NULL, 376, 138, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.parsers", NULL, 377, 261, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.parsers.expat", NULL, 378, 299, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.sax", NULL, 379, 3154, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.sax._exceptions", NULL, 380, 5409, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.sax.expatreader", NULL, 381, 12545, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.sax.handler", NULL, 382, 12387, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.sax.saxutils", NULL, 383, 12886, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xml.sax.xmlreader", NULL, 384, 16809, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xmlrpc", NULL, 385, 84, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xmlrpc.client", NULL, 386, 34532, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"xmlrpc.server", NULL, 387, 29337, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"zipapp", NULL, 388, 5948, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"zipfile", NULL, 389, 58857, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"zoneinfo", NULL, 390, 765, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"zoneinfo._common", NULL, 391, 3069, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"zoneinfo._tzpath", NULL, 392, 4010, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {"zoneinfo._zoneinfo", NULL, 393, 15431, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG
#if PYTHON_VERSION >= 0x370 && !defined(_NUITKA_STANDALONE)
, NULL
#endif
},
    {NULL, NULL, 0, 0, 0}
};

static void _loadBytesCodesBlob()
{
    static bool init_done = false;

    if (init_done == false) {
        loadConstantsBlob((PyObject **)bytecode_data, ".bytecode");

        init_done = true;
    }
}


void setupMetaPathBasedLoader(void) {
    static bool init_done = false;
    if (init_done == false) {
        _loadBytesCodesBlob();
        registerMetaPathBasedUnfreezer(meta_path_loader_entries, bytecode_data);

        init_done = true;
    }


}

// This provides the frozen (compiled bytecode) files that are included if
// any.

// These modules should be loaded as bytecode. They may e.g. have to be loadable
// during "Py_Initialize" already, or for irrelevance, they are only included
// in this un-optimized form. These are not compiled by Nuitka, and therefore
// are not accelerated at all, merely bundled with the binary or module, so
// that CPython library can start out finding them.

struct frozen_desc {
    char const *name;
    int index;
    int size;
};

static struct frozen_desc _frozen_modules[] = {
    {"_collections_abc", 27, 31669},
    {"abc", 39, 5738},
    {"ast", 41, 52269},
    {"codecs", 81, 33851},
    {"collections", 83, -48055},
    {"collections.abc", 84, 31668},
    {"contextlib", 92, 19451},
    {"copyreg", 95, 4393},
    {"dis", 110, 15783},
    {"encodings", 111, -3851},
    {"encodings.aliases", 112, 6293},
    {"encodings.ascii", 113, 1846},
    {"encodings.big5", 115, 1374},
    {"encodings.big5hkscs", 116, 1384},
    {"encodings.charmap", 118, 2856},
    {"encodings.cp037", 119, 2387},
    {"encodings.cp1006", 120, 2463},
    {"encodings.cp1026", 121, 2391},
    {"encodings.cp1125", 122, 8094},
    {"encodings.cp1140", 123, 2377},
    {"encodings.cp1250", 124, 2414},
    {"encodings.cp1251", 125, 2411},
    {"encodings.cp1252", 126, 2414},
    {"encodings.cp1253", 127, 2427},
    {"encodings.cp1254", 128, 2416},
    {"encodings.cp1255", 129, 2435},
    {"encodings.cp1256", 130, 2413},
    {"encodings.cp1257", 131, 2421},
    {"encodings.cp1258", 132, 2419},
    {"encodings.cp273", 133, 2373},
    {"encodings.cp424", 134, 2417},
    {"encodings.cp437", 135, 7811},
    {"encodings.cp500", 136, 2387},
    {"encodings.cp720", 137, 2484},
    {"encodings.cp737", 138, 8133},
    {"encodings.cp775", 139, 7841},
    {"encodings.cp850", 140, 7472},
    {"encodings.cp852", 141, 7849},
    {"encodings.cp855", 142, 8102},
    {"encodings.cp856", 143, 2449},
    {"encodings.cp857", 144, 7452},
    {"encodings.cp858", 145, 7442},
    {"encodings.cp860", 146, 7790},
    {"encodings.cp861", 147, 7805},
    {"encodings.cp862", 148, 7994},
    {"encodings.cp863", 149, 7805},
    {"encodings.cp864", 150, 7949},
    {"encodings.cp865", 151, 7805},
    {"encodings.cp866", 152, 8138},
    {"encodings.cp869", 153, 7829},
    {"encodings.cp874", 154, 2515},
    {"encodings.cp875", 155, 2384},
    {"encodings.cp932", 156, 1376},
    {"encodings.cp949", 157, 1376},
    {"encodings.cp950", 158, 1376},
    {"encodings.euc_jis_2004", 159, 1390},
    {"encodings.euc_jisx0213", 160, 1390},
    {"encodings.euc_jp", 161, 1378},
    {"encodings.euc_kr", 162, 1378},
    {"encodings.gb18030", 163, 1380},
    {"encodings.gb2312", 164, 1378},
    {"encodings.gbk", 165, 1372},
    {"encodings.hp_roman8", 167, 2588},
    {"encodings.hz", 168, 1370},
    {"encodings.iso2022_jp", 170, 1391},
    {"encodings.iso2022_jp_1", 171, 1395},
    {"encodings.iso2022_jp_2", 172, 1395},
    {"encodings.iso2022_jp_2004", 173, 1401},
    {"encodings.iso2022_jp_3", 174, 1395},
    {"encodings.iso2022_jp_ext", 175, 1399},
    {"encodings.iso2022_kr", 176, 1391},
    {"encodings.iso8859_1", 177, 2386},
    {"encodings.iso8859_10", 178, 2391},
    {"encodings.iso8859_11", 179, 2485},
    {"encodings.iso8859_13", 180, 2394},
    {"encodings.iso8859_14", 181, 2412},
    {"encodings.iso8859_15", 182, 2391},
    {"encodings.iso8859_16", 183, 2393},
    {"encodings.iso8859_2", 184, 2386},
    {"encodings.iso8859_3", 185, 2393},
    {"encodings.iso8859_4", 186, 2386},
    {"encodings.iso8859_5", 187, 2387},
    {"encodings.iso8859_6", 188, 2431},
    {"encodings.iso8859_7", 189, 2394},
    {"encodings.iso8859_8", 190, 2425},
    {"encodings.iso8859_9", 191, 2386},
    {"encodings.johab", 192, 1376},
    {"encodings.koi8_r", 193, 2438},
    {"encodings.koi8_t", 194, 2349},
    {"encodings.koi8_u", 195, 2424},
    {"encodings.kz1048", 196, 2401},
    {"encodings.latin_1", 197, 1858},
    {"encodings.mac_arabic", 198, 7705},
    {"encodings.mac_croatian", 199, 2433},
    {"encodings.mac_cyrillic", 200, 2423},
    {"encodings.mac_farsi", 201, 2367},
    {"encodings.mac_greek", 202, 2407},
    {"encodings.mac_iceland", 203, 2426},
    {"encodings.mac_latin2", 204, 2567},
    {"encodings.mac_roman", 205, 2424},
    {"encodings.mac_romanian", 206, 2434},
    {"encodings.mac_turkish", 207, 2427},
    {"encodings.palmos", 208, 2414},
    {"encodings.ptcp154", 209, 2508},
    {"encodings.punycode", 210, 6272},
    {"encodings.quopri_codec", 211, 2359},
    {"encodings.raw_unicode_escape", 212, 1727},
    {"encodings.shift_jis", 214, 1384},
    {"encodings.shift_jis_2004", 215, 1394},
    {"encodings.shift_jisx0213", 216, 1394},
    {"encodings.tis_620", 217, 2476},
    {"encodings.undefined", 218, 2060},
    {"encodings.unicode_escape", 219, 1707},
    {"encodings.utf_16", 220, 4835},
    {"encodings.utf_16_be", 221, 1615},
    {"encodings.utf_16_le", 222, 1615},
    {"encodings.utf_32", 223, 4728},
    {"encodings.utf_32_be", 224, 1508},
    {"encodings.utf_32_le", 225, 1508},
    {"encodings.utf_7", 226, 1536},
    {"encodings.utf_8", 227, 1595},
    {"encodings.utf_8_sig", 228, 4507},
    {"encodings.uu_codec", 229, 3195},
    {"encodings.zlib_codec", 230, 3043},
    {"enum", 231, 25983},
    {"functools", 238, 28145},
    {"genericpath", 239, 3987},
    {"heapq", 247, 14003},
    {"importlib", 255, -3787},
    {"importlib._bootstrap", 256, 28931},
    {"importlib._bootstrap_external", 257, 45133},
    {"importlib.machinery", 260, 927},
    {"inspect", 264, 81354},
    {"io", 265, 3371},
    {"keyword", 272, 879},
    {"linecache", 273, 3990},
    {"locale", 274, 34659},
    {"opcode", 286, 5186},
    {"operator", 287, 13711},
    {"os", 288, 31609},
    {"posixpath", 296, 10292},
    {"quopri", 302, 5710},
    {"re", 304, 14325},
    {"reprlib", 305, 5270},
    {"sre_compile", 318, 15016},
    {"sre_constants", 319, 6280},
    {"sre_parse", 320, 21566},
    {"stat", 322, 4335},
    {"token", 336, 2459},
    {"tokenize", 337, 17100},
    {"types", 342, 9184},
    {"warnings", 352, 13568},
    {NULL, 0, 0}
};


void copyFrozenModulesTo(struct _frozen *destination) {
    _loadBytesCodesBlob();

    struct frozen_desc *current = _frozen_modules;

    for (;;) {
        destination->name = (char *)current->name;
        destination->code = bytecode_data[current->index];
        destination->size = current->size;

        if (destination->name == NULL) break;

        current += 1;
        destination += 1;
    };
}

